Домашнее задание №1
oparinanna/2020-1-Atom-QA-Python-A-Oparina pull request #1
Opened 2020-03-02 22:08 UTC by oparinanna

# Домашнее задание №1

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:
* Написано по 5 тестов на каждую из 5-ти стуктур данных: int, string, list, dict, set.
* Тесты для каждой структуры лежат в отдельных файлах (для int тесты лежат в файле test_int и т.д.).
* Для каждой структуры написано по одному параметризованному тесту.
* Часть тестов лежит в классе.

2020-03-04 20:41 UTC, sniiick requested changes
Мелкие замечания

2020-03-04 20:41 UTC, sniiick commented on homework_1/Pipfile
> +[[source]]
На 1 лекции договорились что в проект кладем requirements.txt
.lock файл аналогично

2020-03-04 20:41 UTC, sniiick commented on homework_1/test_list.py
> +        a = [1,2,3]
пробелы после запятой во всем файле

2020-03-04 20:41 UTC, sniiick commented on pull_request_template.md
> +# Домашнее задание №1
Сам темплейт править не надо. Он создан для того чтобы его подцепил гитхаб и можно было отредактировать описание при создании ПР.

2020-03-06 21:20 UTC, oparinanna commented on homework_1/Pipfile
> +[[source]]
Записала в requirements.txt вывод pip freeze. 
У меня есть Pipfile.lock - это то, что нужно или нет?

2020-03-07 16:06 UTC, snicks92 commented on homework_1/Pipfile
> +[[source]]
Pipfile и pipfile.lock теперь нужно удалить из проекта

2020-03-07 16:08 UTC, sniiick reviewed
Давай удалим Pipfile и Pipfile.lock и приму ДЗ

2020-03-07 20:14 UTC, oparinanna commented on homework_1/Pipfile
> +[[source]]
Удалила файлы pipfile и Pipfile.lock

2020-03-07 20:15 UTC, sniiick approved these changes

2020-03-07 20:15 UTC, merged